# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import client.src.sima_grpc.protobuf_grpc.product_pb2 as product__pb2


class ProductStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ViewBySids = channel.unary_unary(
                '/simaland.product.proto.Product/ViewBySids',
                request_serializer=product__pb2.BySidsRequest.SerializeToString,
                response_deserializer=product__pb2.ItemsResponse.FromString,
                )
        self.ViewByIds = channel.unary_unary(
                '/simaland.product.proto.Product/ViewByIds',
                request_serializer=product__pb2.ByIdsRequest.SerializeToString,
                response_deserializer=product__pb2.ItemsResponse.FromString,
                )
        self.ViewByWBBarcodes = channel.unary_unary(
                '/simaland.product.proto.Product/ViewByWBBarcodes',
                request_serializer=product__pb2.ByWBBarcodesRequest.SerializeToString,
                response_deserializer=product__pb2.ItemsResponse.FromString,
                )
        self.ViewByUuids = channel.unary_unary(
                '/simaland.product.proto.Product/ViewByUuids',
                request_serializer=product__pb2.ByUuidsRequest.SerializeToString,
                response_deserializer=product__pb2.ItemsResponse.FromString,
                )
        self.ScanByParentId = channel.unary_unary(
                '/simaland.product.proto.Product/ScanByParentId',
                request_serializer=product__pb2.ByOffsetRequest.SerializeToString,
                response_deserializer=product__pb2.ScanByParentIdResponse.FromString,
                )
        self.ViewByParentIds = channel.unary_unary(
                '/simaland.product.proto.Product/ViewByParentIds',
                request_serializer=product__pb2.ByParentIdsRequest.SerializeToString,
                response_deserializer=product__pb2.ParentItemsResponse.FromString,
                )
        self.ScanByGroupId = channel.unary_unary(
                '/simaland.product.proto.Product/ScanByGroupId',
                request_serializer=product__pb2.ByOffsetRequest.SerializeToString,
                response_deserializer=product__pb2.ScanByGroupIdResponse.FromString,
                )
        self.ViewByGroupIds = channel.unary_unary(
                '/simaland.product.proto.Product/ViewByGroupIds',
                request_serializer=product__pb2.ByGroupIdsRequest.SerializeToString,
                response_deserializer=product__pb2.GroupItemsResponse.FromString,
                )


class ProductServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ViewBySids(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewByWBBarcodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewByUuids(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanByParentId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewByParentIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanByGroupId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewByGroupIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ViewBySids': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewBySids,
                    request_deserializer=product__pb2.BySidsRequest.FromString,
                    response_serializer=product__pb2.ItemsResponse.SerializeToString,
            ),
            'ViewByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewByIds,
                    request_deserializer=product__pb2.ByIdsRequest.FromString,
                    response_serializer=product__pb2.ItemsResponse.SerializeToString,
            ),
            'ViewByWBBarcodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewByWBBarcodes,
                    request_deserializer=product__pb2.ByWBBarcodesRequest.FromString,
                    response_serializer=product__pb2.ItemsResponse.SerializeToString,
            ),
            'ViewByUuids': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewByUuids,
                    request_deserializer=product__pb2.ByUuidsRequest.FromString,
                    response_serializer=product__pb2.ItemsResponse.SerializeToString,
            ),
            'ScanByParentId': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanByParentId,
                    request_deserializer=product__pb2.ByOffsetRequest.FromString,
                    response_serializer=product__pb2.ScanByParentIdResponse.SerializeToString,
            ),
            'ViewByParentIds': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewByParentIds,
                    request_deserializer=product__pb2.ByParentIdsRequest.FromString,
                    response_serializer=product__pb2.ParentItemsResponse.SerializeToString,
            ),
            'ScanByGroupId': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanByGroupId,
                    request_deserializer=product__pb2.ByOffsetRequest.FromString,
                    response_serializer=product__pb2.ScanByGroupIdResponse.SerializeToString,
            ),
            'ViewByGroupIds': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewByGroupIds,
                    request_deserializer=product__pb2.ByGroupIdsRequest.FromString,
                    response_serializer=product__pb2.GroupItemsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simaland.product.proto.Product', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Product(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ViewBySids(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simaland.product.proto.Product/ViewBySids',
            product__pb2.BySidsRequest.SerializeToString,
            product__pb2.ItemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ViewByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simaland.product.proto.Product/ViewByIds',
            product__pb2.ByIdsRequest.SerializeToString,
            product__pb2.ItemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ViewByWBBarcodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simaland.product.proto.Product/ViewByWBBarcodes',
            product__pb2.ByWBBarcodesRequest.SerializeToString,
            product__pb2.ItemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ViewByUuids(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simaland.product.proto.Product/ViewByUuids',
            product__pb2.ByUuidsRequest.SerializeToString,
            product__pb2.ItemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ScanByParentId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simaland.product.proto.Product/ScanByParentId',
            product__pb2.ByOffsetRequest.SerializeToString,
            product__pb2.ScanByParentIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ViewByParentIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simaland.product.proto.Product/ViewByParentIds',
            product__pb2.ByParentIdsRequest.SerializeToString,
            product__pb2.ParentItemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ScanByGroupId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simaland.product.proto.Product/ScanByGroupId',
            product__pb2.ByOffsetRequest.SerializeToString,
            product__pb2.ScanByGroupIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ViewByGroupIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simaland.product.proto.Product/ViewByGroupIds',
            product__pb2.ByGroupIdsRequest.SerializeToString,
            product__pb2.GroupItemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
