# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import product_pb2 as product__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13product_event.proto\x12\x16simaland.product.proto\x1a\rproduct.proto\"M\n\tItemEvent\x12\x11\n\tisDeleted\x18\x01 \x01(\x08\x12-\n\x07payload\x18\x02 \x01(\x0b\x32\x1c.simaland.product.proto.Item\"p\n\x12ItemStockInfoEvent\x12\x11\n\tisDeleted\x18\x01 \x01(\x08\x12\x0e\n\x06itemId\x18\x02 \x01(\x05\x12\x37\n\x07payload\x18\x03 \x03(\x0b\x32&.simaland.product.proto.Item.StockInfo\"v\n\x15ItemSpecialOfferEvent\x12\x11\n\tisDeleted\x18\x01 \x01(\x08\x12\x0e\n\x06itemId\x18\x02 \x01(\x05\x12:\n\x07payload\x18\x03 \x03(\x0b\x32).simaland.product.proto.Item.SpecialOffer\"p\n\x12ItemAttributeEvent\x12\x11\n\tisDeleted\x18\x01 \x01(\x08\x12\x0e\n\x06itemId\x18\x02 \x01(\x05\x12\x37\n\x07payload\x18\x03 \x03(\x0b\x32&.simaland.product.proto.Item.Attribute\"x\n\x16ItemPersonalPriceEvent\x12\x11\n\tisDeleted\x18\x01 \x01(\x08\x12\x0e\n\x06itemId\x18\x02 \x01(\x05\x12;\n\x07payload\x18\x03 \x03(\x0b\x32*.simaland.product.proto.Item.PersonalPrice\"f\n\x16UserPersonalPriceEvent\x12\x11\n\tisDeleted\x18\x01 \x01(\x08\x12\x0e\n\x06userID\x18\x02 \x01(\x05\x12\x16\n\x0especialOfferID\x18\x03 \x01(\x05\x12\x11\n\tpriceType\x18\x04 \x01(\x05\x42\x1aZ\x18/;simaland_product_protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_event_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\030/;simaland_product_proto'
  _globals['_ITEMEVENT']._serialized_start=62
  _globals['_ITEMEVENT']._serialized_end=139
  _globals['_ITEMSTOCKINFOEVENT']._serialized_start=141
  _globals['_ITEMSTOCKINFOEVENT']._serialized_end=253
  _globals['_ITEMSPECIALOFFEREVENT']._serialized_start=255
  _globals['_ITEMSPECIALOFFEREVENT']._serialized_end=373
  _globals['_ITEMATTRIBUTEEVENT']._serialized_start=375
  _globals['_ITEMATTRIBUTEEVENT']._serialized_end=487
  _globals['_ITEMPERSONALPRICEEVENT']._serialized_start=489
  _globals['_ITEMPERSONALPRICEEVENT']._serialized_end=609
  _globals['_USERPERSONALPRICEEVENT']._serialized_start=611
  _globals['_USERPERSONALPRICEEVENT']._serialized_end=713
# @@protoc_insertion_point(module_scope)
